### ISSUE TITLE
Possible bug when setting crd field

### ISSUE THREAD

**Issue by onahman** [almaan/sepal#2] opened 2021-03-21 16:22 UTC
Even after I manually set 'x' and 'y' in my anndata, the crd field returned empty.
Closely looking at the code revealed a potential problem:
_datasets.py line 168:_
```
            if 'x' in tmp.obs.keys() and 'y' in tmp.obs.keys():

                self._crd['pixel'] = np.zeros((n_spots,2))
                self._crd['pixel'][:,0] = tmp.obs['x'].values
                self._crd['pixel'][:,1] = tmp.obs['y'].values

            else:
                self._crd['pixel'] = None
            # set array coordinates as _x,_y
            if '_x' in tmp.obs.keys() and '_y' in tmp.obs.keys():

                self._crd['array'] = np.zeros((n_spots,2))
                self._crd['array'][:,0] = tmp.obs['_x'].values
                self._crd['array'][:,1] = tmp.obs['_y'].values
            else:
                self._crd['array'] = np.array([])
                self._crd['pixel'] = np.array([])   <------- This line should be deleted?
```
The last line overrides the 'pixel' definition of the first 'if' clause

**Comment by almaan** [comment] 2021-03-22 06:17
Hello again @onahman,

it's wonderful to see how diligent you looked through the code and thank you for reporting this. However, this is not a bug but rather intended to set the "array" and "pixel" coordinates to empty arrays if no spatial data is found in the anndata object. This is again a consequence of me using a slightly different anndata format than scanpy (see my answer to your previous issue, and check [this](https://github.com/almaan/sepal#supported-files-and-format) section of the README). 

I'm planning on: (i) making sepal compatible with `scanpy` visium format and (ii) make `sepal` available as a module in `squidpy` but none of these items were available at the time of submission, hence I've waited with their implementations until publication of the manuscript.

Best
Alma

**Comment by almaan** [comment] 2021-03-22 06:41
Hello again @onahman,

it's wonderful to see how diligent you looked through the code and thank you for reporting this. Well spotted, I'll push some new code asap to take care of this.

Best
Alma

**Comment by almaan** [comment] 2021-03-25 08:53
I will also close this issue, as this was discussed in a [related issue](https://github.com/almaan/sepal/issues/1) (now closed).

**Closed as completed by almaan** 2021-03-25 08:53 UTC
